### ISSUE TITLE
Is the function "Recon_sqSTFT_v2" missing?

### ISSUE THREAD

**Issue by zhangyi84688** [Acicone/SIFT_paper#1]

**Comment by Acicone** [comment]
Dear user,
thanks for your feedback.
Yes you are right, the file was missing.
I just added to the repository.
Please let us know if you encounter any other problem.
Best regards

**Comment by zhangyi84688** [comment]
Dear Antonio,
Thanks for your reply, I still have some questions to discuss with you.
1.opt = Settings_ALIF('ALIF.NIMTs',1,'plots',0,'saveplots',0,'ALIF.xi',1.4,'ALIF.delta',10^-6); 
where'ALIF. NIMTs' should be ALIF.NIMFs';
2.function [recon] = Recon_sqSTFT_v2(tfrsq, tfrsqtic, Hz, c, Band) .There are 5 function parameters, and the parameters in Example 1 are indeed 6;
 [IMT_SST] = Recon_sqSTFT_v2(tfrsq, tfrsqtic, Hz, curve_n(: ,1), Band, h((WindowLength+1)/2));
Is there an extra parameter written in the function?
3. Is the "bandpass" function missing?
Looking forward to your reply.
Best regards


| |
yizhang_de
|
|
yizhang_de@163.com
|
签名由网易邮箱大师定制
On 7/17/2020 13:14，Antonio Cicone<notifications@github.com> wrote：

Dear user,
thanks for your feedback.
Yes you are right, the file was missing.
I just added to the repository.
Please let us know if you encounter any other problem.
Best regards

**Comment by Acicone** [comment]
Dear Yi,
regarding your questions:
1) yes, 'ALIF. NIMTs' should be ALIF.NIMFs'. 
I fixed this issue and updated the m files you find in the repository
2) You are right. I uploaded an old version of the same code. Now you can find the last version of this function.
3) bandpass is a Matlab function
Thanks a lot for all these feedback. 
Feel free to contact me if you need further assistance.
Best regards

**Comment by zhangyi84688** [comment]
> Dear Yi,
> regarding your questions:
> 
> 1. yes, 'ALIF. NIMTs' should be ALIF.NIMFs'.
>    I fixed this issue and updated the m files you find in the repository
> 2. You are right. I uploaded an old version of the same code. Now you can find the last version of this function.
> 3. bandpass is a Matlab function
>    Thanks a lot for all these feedback.
>    Feel free to contact me if you need further assistance.
>    Best regards
Dear Antonio,
thank you for your reply.
The "bandpass" function is not found in the version of matlab R2014a I use. Can you share this function with the version you use and share it with me? My email is yizhang_de@163.com or zhangyi93@wust.edu.cn
Looking forward to your reply
Best regards

**Comment by zhangyi84688** [comment]
Dear Antonio Cicone,
thank you for your reply.
The "bandpass" function is not found in the version of matlab R2014a I use. Can you share this function with the version you use and share it with me? My email is yizhang_de@163.com or zhangyi93@wust.edu.cn
Looking forward to your reply
Best regards


| |
yizhang_de
|
|
yizhang_de@163.com
|

**Comment by Acicone** [comment]
Dear Yi,
I'm using Matlab version 2020 a, but I remember using bandpass function also with version 2018 b, if I remember right.
There is no way to share a build in function because it makes use of many other predefined functions.
The only solution for you is to either upgrade Matlab to a recent version or to look for an equivalent function written by someone.
Best regards
